version: "3.9"
services:
  cloudtunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=
    networks:
      - cloudflared

networks:
  cloudflared: