version: '3.7'
services:
  librespeedtest:
    image: linuxserver/librespeed:latest
    container_name: LibreSpeedTest
    restart: unless-stopped
    networks:
      - portainer-traefik_default
    #ports:
      #- 8123:80
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Jakarta
      - CUSTOM_RESULTS=false
      - PASSWORD="sekritpassword"
    volumes:
      - ./config:/config
    labels:
      - traefik.enable=true
      - traefik.http.services.librespeed.loadbalancer.server.port=80
      - traefik.http.routers.librespeed.rule=Host(`speedtest.domain.id`)
      - traefik.http.routers.librespeed.tls.certresolver=letsencrypt
      - traefik.http.routers.librespeed.entrypoints=websecure
networks:
  portainer-traefik_default:
    external: true
