version: '3.7'
services:
  librespeed-front:
    image: adolfintel/speedtest
    container_name: librespeed-frontend
    restart: unless-stopped
    environment:
      - MODE=frontend 
      - TELEMETRY=true 
      - ENABLE_ID_OBFUSCATION=true 
      - PASSWORD=passwordhere
      - TITLE=KoronSpeed
    volumes:
      - ./servers.json:/servers.json
      - ./html:/var/www/html  #Directory to customize index.php
    #ports:
    #  - 8888:80
    #labels:
      #Traefik frontend domain
      #- traefik.enable=true
      #- traefik.http.services.librefront.loadbalancer.server.port=80
      #- traefik.http.routers.librefront.rule=Host(`speedtest-front.domain.id`)
      #- traefik.http.routers.librefront.tls.certresolver=letsencrypt
      #- traefik.http.routers.librefront.entrypoints=websecure
      #- traefik.http.routers.librefront.service=librefront
    networks:
      - portainer-default
  librespeed-back:
    image: adolfintel/speedtest
    container_name: librespeed-backend
    restart: unless-stopped
    environment:
      - MODE=backend
      - IPINFO_APIKEY= #APIKey ipinfo.io
    #ports:
    #  - 8880:80
    #labels:
      #Traefik backend domain
      #- traefik.enable=true
      #- traefik.http.services.librefront.loadbalancer.server.port=80
      #- traefik.http.routers.librefront.rule=Host(`speedtest-back.domain.id`)
      #- traefik.http.routers.librefront.tls.certresolver=letsencrypt
      #- traefik.http.routers.librefront.entrypoints=websecure
      #- traefik.http.routers.librefront.service=librefront
    networks:
      - portainer-default

#Using existing docker network
networks:
  portainer-default:
    external: true
