version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock #Docker setup, not recommended because of security concern.
    #ports:
      #- 3001:3001  # <Host Port>:<Container Port>
    networks:
      - portainer-traefik_default  #existing docker network
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.kuma.loadbalancer.server.port=3001
      - traefik.http.routers.kuma.rule=Host(`kuma.domain.id`) #admin subdomain
      - traefik.http.routers.kuma.tls.certresolver=letsencrypt
      - traefik.http.routers.kuma.entrypoints=websecure
      - traefik.http.routers.kuma.service=kuma
      - traefik.http.routers.kuma.tls=true
      - traefik.http.services.kumastat.loadbalancer.server.port=3001
      - traefik.http.routers.kumastat.rule=Host(`up.domain.id`) #status subdomain
      - traefik.http.routers.kumastat.tls.certresolver=letsencrypt
      - traefik.http.routers.kumastat.entrypoints=websecure
      - traefik.http.routers.kumastat.service=kumastat
      - traefik.http.routers.kumastat.tls=true

networks:
  portainer-traefik_default: #existing docker network
    external: true

    