version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      #- 3001:3001  # <Host Port>:<Container Port>
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.kuma.loadbalancer.server.port=3001
      - traefik.http.routers.kuma.rule=Host(`kuma.domain.id`)
      - traefik.http.routers.kuma.tls.certresolver=letsencrypt
      - traefik.http.routers.kuma.entrypoints=websecure
      - traefik.http.routers.kuma.service=kuma

    